name: Flutter CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'

      # Get flutter dependencies
      - run: dart pub get

      # Format check
      - run: dart format --set-exit-if-changed .

      # Analyze
      - run: dart analyze .
      # Widget test
      # - run: flutter test
      # Building APK
      # - run: flutter build apk
      # - name: Upload APK
      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: release-apk
      #     path: build/app/outputs/apk/release/app-release.apk
